"""Interactive first-run setup for hermes-relay."""

from __future__ import annotations

import argparse
import asyncio
import getpass
import inspect
import json
import os
import tempfile
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit, urlunsplit

import yaml

import config
from voice import DEFAULT_STT_MODEL


DEFAULT_TOKEN_ENV_PATH = config.DEFAULT_PROFILE_ENV


def prepare_stt_model(model_name: str) -> str:
    """Download the local Faster-Whisper model and return its cache path."""
    model = str(model_name or DEFAULT_STT_MODEL).strip()
    if not model:
        model = DEFAULT_STT_MODEL

    local_path = Path(model).expanduser()
    if local_path.exists():
        if not local_path.is_dir():
            raise ValueError(f"STT model path is not a directory: {local_path}")
        return str(local_path)

    try:
        from faster_whisper import download_model
    except ImportError as exc:
        raise RuntimeError(
            "local voice dependencies are unavailable; install requirements-dev.txt"
        ) from exc
    return str(download_model(model))


def _ask(input_fn: Any, question: str, *, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    return str(input_fn(f"{question}{suffix}: ") or "").strip() or default


def _existing_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ValueError(f"config file {path} must contain a mapping")
    return value


def normalize_endpoint(value: str) -> str:
    """Normalize a pasted HTTP(S) or WebSocket voice-session endpoint."""
    raw = str(value or "").strip()
    if raw.startswith("http://"):
        raw = "ws://" + raw[len("http://") :]
    elif raw.startswith("https://"):
        raw = "wss://" + raw[len("https://") :]
    parsed = urlsplit(raw)
    if parsed.scheme not in {"ws", "wss"} or not parsed.netloc:
        raise ValueError("endpoint must be a ws:// or wss:// URL")
    path = parsed.path.rstrip("/")
    if path.endswith("/health"):
        path = path[: -len("/health")].rstrip("/")
    return urlunsplit((parsed.scheme, parsed.netloc, path or "/voice-session", parsed.query, ""))


def _write_private_env(path: Path, token: str) -> None:
    if not token or any(char in token for char in "\r\n"):
        raise ValueError("voice-session token must be a non-empty single line")

    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True) if path.exists() else []
    replacement = f"VOICE_SESSION_TOKEN={json.dumps(token)}\n"
    for index, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith("VOICE_SESSION_TOKEN=") or stripped.startswith("export VOICE_SESSION_TOKEN="):
            lines[index] = replacement
            break
    else:
        if lines and not lines[-1].endswith("\n"):
            lines[-1] += "\n"
        lines.append(replacement)

    fd, temporary = tempfile.mkstemp(dir=path.parent, prefix=".env.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.writelines(lines)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        os.chmod(path, 0o600)
    except BaseException:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def save_setup_files(
    *,
    config_path: Path,
    token_path: Path,
    url: str,
    token: str,
    client_id: str,
    device_id: str,
    session_id: str,
    display_name: str,
    stt_model: str | None = None,
) -> None:
    """Persist setup answers without placing the bearer token in YAML."""
    if config_path.exists():
        existing = yaml.safe_load(config_path.read_text(encoding="utf-8"))
        if existing is None:
            config: dict[str, Any] = {}
        elif isinstance(existing, dict):
            config = existing
        else:
            raise ValueError(f"config file {config_path} must contain a mapping")
    else:
        config = {}

    config.update(
        {
            "url": url,
            "profile_env": str(token_path),
            "client_id": client_id,
            "device_id": device_id,
            "session_id": session_id,
            "display_name": display_name,
        }
    )
    if stt_model:
        config["stt_model"] = stt_model

    config_path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    config_path.write_text(
        "# Generated by `hermes-relay setup`; edit this file to change defaults.\n"
        + yaml.safe_dump(config, sort_keys=False),
        encoding="utf-8",
    )
    os.chmod(config_path, 0o600)
    _write_private_env(token_path, token)


def run_setup(
    argv: list[str] | None = None,
    *,
    config_path: Path | None = None,
    token_path: Path | None = None,
    input_fn: Any = input,
    secret_fn: Any = getpass.getpass,
    output_fn: Any = print,
    check_connection: bool = True,
    connection_check_fn: Any = None,
) -> int:
    """Ask for connection details and save an editable local setup."""
    parser = argparse.ArgumentParser(prog="hermes-relay setup")
    parser.add_argument(
        "--config",
        type=Path,
        default=config_path or config.DEFAULT_CONFIG_PATH,
        help="editable YAML config path",
    )
    parser.add_argument(
        "--token-file",
        type=Path,
        default=token_path,
        help="private .env path for the bearer token",
    )
    parser.add_argument(
        "--stt-model",
        default=None,
        help=f"local Faster-Whisper model to prepare (default: {DEFAULT_STT_MODEL})",
    )
    parser.add_argument("--no-check", action="store_true", help="save without testing the relay")
    args = parser.parse_args([] if argv is None else argv)
    config_path = args.config.expanduser()
    if connection_check_fn is None:
        connection_check_fn = probe_connection

    try:
        existing = _existing_config(config_path)
    except (OSError, UnicodeDecodeError, yaml.YAMLError, ValueError) as exc:
        output_fn(f"Setup failed: {exc}")
        return 1
    if args.token_file is not None:
        token_path = args.token_file
    elif existing.get("profile_env"):
        token_path = Path(str(existing["profile_env"]))
    else:
        token_path = DEFAULT_TOKEN_ENV_PATH
    token_path = token_path.expanduser()

    output_fn("Hermes Relay setup")
    output_fn(f"Config file: {config_path}")
    output_fn("The bearer token is stored separately in a private .env file.")
    output_fn("Copy the WebSocket endpoint and token from the Hermes server setup.")

    url = _ask(input_fn, "Hermes WebSocket URL", default=str(existing.get("url") or ""))
    if not url:
        output_fn("Setup cancelled: a WebSocket URL is required.")
        return 1
    try:
        url = normalize_endpoint(url)
    except ValueError as exc:
        output_fn(f"Setup cancelled: {exc}.")
        return 1

    token = str(secret_fn("Bearer token (hidden; leave blank to keep the current token): ") or "").strip()
    if not token:
        try:
            token = config._resolve_token(None, token_path)
        except (OSError, UnicodeDecodeError):
            token = ""
    if not token:
        output_fn("Setup cancelled: a bearer token is required.")
        return 1

    client_id = _ask(input_fn, "Client ID", default=str(existing.get("client_id") or "hermes-relay"))
    device_id = str(existing.get("device_id") or config.default_device_id())
    session_id = _ask(input_fn, "Session ID", default=str(existing.get("session_id") or "default"))
    display_name = str(existing.get("display_name") or f"{client_id} relay")
    stt_model = (
        args.stt_model
        or os.getenv("VOICE_SESSION_STT_MODEL")
        or str(existing.get("stt_model") or DEFAULT_STT_MODEL)
    )

    output_fn(f"Preparing local speech model '{stt_model}'...")
    try:
        model_path = prepare_stt_model(stt_model)
    except Exception as exc:
        output_fn(f"Setup failed: local speech model could not be prepared: {exc}")
        return 1

    try:
        save_setup_files(
            config_path=config_path,
            token_path=token_path,
            url=url,
            token=token,
            client_id=client_id,
            device_id=device_id,
            session_id=session_id,
            display_name=display_name,
            stt_model=stt_model,
        )
    except (OSError, UnicodeDecodeError, ValueError, yaml.YAMLError) as exc:
        output_fn(f"Setup failed: {exc}")
        return 1

    output_fn(
        f"Local speech model ready at {model_path}."
    )
    output_fn(f"Setup complete. Edit {config_path} to change these defaults.")
    if check_connection and not args.no_check and connection_check_fn is not None:
        result = connection_check_fn(url, token, client_id, device_id, session_id)
        if inspect.isawaitable(result):
            result = asyncio.run(result)
        ok, message = result
        output_fn(message)
        return 0 if ok else 1
    return 0


async def probe_connection(
    url: str,
    token: str,
    client_id: str,
    device_id: str,
    session_id: str,
    *,
    connect_factory: Any = None,
    timeout: float = 10.0,
) -> tuple[bool, str]:
    """Verify credentials and protocol compatibility without sending a turn."""
    connect = connect_factory or config.connect_factory()
    try:
        async with connect(url, **config._connection_kwargs(connect, token)) as websocket:
            await websocket.send(
                json.dumps(
                    {
                        "type": "hello",
                        "protocol_version": 1,
                        "client_id": client_id,
                        "device_id": device_id,
                        "session_id": session_id,
                        "display_name": f"{client_id} relay",
                    }
                )
            )
            while True:
                frame = await asyncio.wait_for(websocket.recv(), timeout=timeout)
                if isinstance(frame, bytes):
                    continue
                payload = json.loads(frame)
                break
    except Exception as exc:
        return False, f"Connection failed: {exc}"

    if payload.get("type") != "hello_ack":
        return False, f"Connection failed: {payload.get('error') or 'server rejected hello'}"
    if payload.get("protocol_version") != 1:
        return False, "Connection failed: server does not support protocol v1"
    return True, f"Connection verified: {payload.get('chat_id') or client_id}"
